### ISSUE TITLE
Collection id

### ISSUE THREAD

**Issue by m8dotpie** [Roguyt/node-epicsgg#4]
CollectionId is a required field when I want to get owned account cards, but where do I get collection id? I can not find any methods listing collections and cards

**Comment by Roguyt** [comment]
There is 2 ways for you to get the collectionID:
- Either by iterating from 1 to N
- Using `User.getUserSummary()`, documented [here](https://roguyt.github.io/node-epicsgg/classes/user.html#getusersummary).
You can either filter by season or just pass an empty string to get all of them.
