### ISSUE TITLE
Wrong seasons handling on user summary

### ISSUE THREAD

**Issue by gjariot** [Roguyt/node-epicsgg#40]
Hey,
Thanks again for the hard work on the library.

There's an issue with seasons handling on the user summary API call. It currently checks for `season` whereas it should be `seasons`.

https://github.com/Roguyt/node-epicsgg/blob/master/src/client/actions/User.ts#L68

The Collection interface built as a result also have an issue, `seasons` is a list of strings whereas the interface specifies a single string.

https://github.com/Roguyt/node-epicsgg/blob/master/src/interfaces/Collection.ts#L12

To reproduce the issue:
```
epics.User.getUserSummary(userId, 2018)
.then(summary => console.log(summary.collections[0].collection.properties.seasons))
```
Should output `2018` based on current code, outputs `['Founders Edition']`

If I can contribute and propose the fix, I just have it prepared and would be glad to help.

**Comment by Roguyt** [comment]
Currently being discussed to be fixed here: https://github.com/Roguyt/node-epicsgg/pull/41
